export const queryKeys = {
  activityDeadlines: () => ['activity-deadlines'] as const,
  das: (companyId: string, filters?: object) => ['das', companyId, filters] as const,
  apuracao: (companyId: string) => ['apuracao', companyId] as const,
  obrigacoes: (companyId: string) => ['obrigacoes', companyId] as const,
  nfeStagingHistory: (companyId: string) => ['nfe-staging', companyId] as const,
  notasEntrada: (companyId: string, filters?: object) => ['notas-entrada', companyId, filters] as const,
  notasSaida: (companyId: string, filters?: object) => ['notas-saida', companyId, filters] as const,
  employees: (companyId: string) => ['employees', companyId] as const,
  minhasSolicitacoesFuncionarios: (companyId: string) => ['minhas-solicitacoes-funcionarios', companyId] as const,
  funcionarioDocumentos: (companyId: string, funcionarioId: string) =>
    ['funcionario-documentos', companyId, funcionarioId] as const,
  holerites: (companyId: string, filters?: object) => ['holerites', companyId, filters] as const,
  accounts: (companyId: string) => ['accounts', companyId] as const,
  documentosResumo: (companyId: string) => ['documentos-resumo', companyId] as const,
  documentosHistorico: (companyId: string, typeId: string, filters?: object) =>
    ['documentos-historico', companyId, typeId, filters] as const,
  dreMensal: (companyId: string, meses?: number) => ['dre-mensal', companyId, meses] as const,
  company: (companyId: string) => ['company', companyId] as const,
  assignment: (companyId: string) => ['assignment', companyId] as const,
  leadStatus: () => ['lead-status'] as const,
  leadDocumentos: () => ['lead-documentos'] as const,
  minhaAbertura: () => ['minha-abertura'] as const,
  aberturaEstrutura: (aberturaId: string) => ['abertura-estrutura', aberturaId] as const,
  minhaTransferencia: () => ['minha-transferencia'] as const,
  minhaTrocaContador: () => ['minha-troca-contador'] as const,
  minhaFaturamentoVerificado: () => ['minha-faturamento-verificado'] as const,
};
